src/java3/mlz/model/AbsMoviesAndDetail.java
package java3.mlz.model;

import java.util.List;

public abstract class AbsMoviesAndDetail {
	private List<Movie> movies;
	// movie detail
	private Movie movieDetail;

	/**
	 * method to show details of the movie
	 * 
	 * @param movie
	 * @return detail page
	 */
	public String show_detail(Movie movie) {
		movieDetail = movie;
		// stay on page
		return "";
	}

	/**
	 * back to the overview
	 * 
	 * @return Link
	 */
	public final String close() {
		movieDetail = null;
		return "";
	}

	/*
	 * getters and setters
	 */

	public List<Movie> getMovies() {
		return movies;
	}

	public void setMovies(List<Movie> movies) {
		this.movies = movies;
	}

	public Movie getMovieDetail() {
		return movieDetail;
	}

	public void setMovieDetail(Movie movie) {
		this.movieDetail = movie;
	}

	/**
	 * Dummy getter to get the size of the movie list.
	 * 
	 * @return
	 */
	public Integer getStoredMovies() {
		return movies.size();
	}
}

src/java3/mlz/model/managed/AddMovieBean.java
package java3.mlz.model.managed;

import java.util.ResourceBundle;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

import java3.mlz.business.Controller;
import java3.mlz.model.Movie;

/**
 * managed bean class to add a movie manually
 * 
 * @author retoweber
 *
 */
@ManagedBean
@ViewScoped
public class AddMovieBean {
	private Movie movie;

	/**
	 * managed bean method to save a movie
	 * 
	 * @param movie
	 * @return
	 */
	public String save() {
		return Controller.saveMovie(movie);
	}

	/**
	 * cancel method to return redirect string.
	 * 
	 * @return
	 */
	public String cancel() {
		return Controller.goToMyMovies();
	}

	/**
	 * Validate runtime with minutes
	 * 
	 * @param context
	 * @param comp
	 * @param value
	 * @throws ValidatorException
	 */
	public void validateRuntime(FacesContext context, UIComponent comp, Object value) throws ValidatorException {
		if (value != null) {
			String strVal = (String) value;
			if (!strVal.isEmpty())
				// could be empty of should match
				if (!strVal.matches("^[0-9]{0,4} min$")) {
					throw new ValidatorException(new FacesMessage(message("runtime_enter_error")));
				}
		}
	}

	/**
	 * Validate poster URL
	 * 
	 * @param context
	 * @param comp
	 * @param value
	 * @throws ValidatorException
	 */
	public void validateUrl(FacesContext context, UIComponent comp, Object value) throws ValidatorException {
		if (value != null) {
			String strVal = (String) value;
			if (!strVal.isEmpty())
				// could be empty of should match
				if (!strVal.matches(
						"^(http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$")) {
					throw new ValidatorException(
							new FacesMessage("Not a correct URL-Format. Example: http(s)://domain.org/filename.jpg"));
				}
		}
	}

	/*
	 * getters and setters
	 */
	public Movie getMovie() {
		// insure that a movie instance exists
		if (movie == null) {
			movie = new Movie();
		}
		return movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	private String message(String key) {
		FacesContext fc = FacesContext.getCurrentInstance();
		ResourceBundle bundle = fc.getApplication().getResourceBundle(fc, "msg");
		return bundle.getString(key);
	}
}

WebContent/add_movie.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="content">
			<h2>
				<h:outputText value="#{msg.add_movie}" />
			</h2>

			<h:form id="form">

				<h:panelGrid id="input_grid" columns="3">

					<h:outputLabel for="title" value="#{msg.title}" />
					<h:inputText id="title" maxlength="1000" required="true"
						value="#{addMovieBean.movie.title}" />
					<h:message for="title" style="color: red" />

					<h:outputLabel for="year" value="#{msg.year}" />
					<h:inputText id="year" maxlength="4"
						value="#{addMovieBean.movie.year}" 
						validator="yearValidator" />
					<h:message for="year" style="color: red" />

					<h:outputLabel for="rated" value="rated" />
					<h:inputText id="rated" maxlength="100"
						value="#{addMovieBean.movie.rated}" />
					<h:message for="rated" style="color: red" />

					<h:outputLabel for="released" value="#{msg.released}" />
					<h:inputText id="released" maxlength="10"
						value="#{addMovieBean.movie.released}">
						<f:convertDateTime pattern="dd.MM.yyyy" />
					</h:inputText>
					<h:message for="released" style="color: red" />

					<h:outputLabel for="runtime" value="#{msg.runtime}" />
					<h:inputText id="runtime" maxlength="8"
						validator="#{addMovieBean.validateRuntime}"
						value="#{addMovieBean.movie.runtime}" />
					<h:message for="runtime" style="color: red" />

					<h:outputLabel for="genre" value="#{msg.genre}" />
					<h:inputText id="genre" maxlength="1000"
						value="#{addMovieBean.movie.genre}" />
					<h:message for="genre" style="color: red" />

					<h:outputLabel for="director" value="Director" />
					<h:inputText id="director" maxlength="1000"
						value="#{addMovieBean.movie.director}" />
					<h:message for="director" style="color: red" />

					<h:outputLabel for="writer" value="Writer" />
					<h:inputText id="writer" maxlength="1000"
						value="#{addMovieBean.movie.writer}" />
					<h:message for="write" style="color: red" />

					<h:outputLabel for="actors" value="#{msg.actors}" />
					<h:inputText id="actors" maxlength="1000"
						value="#{addMovieBean.movie.actors}" />
					<h:message for="actors" style="color: red" />

					<h:outputLabel for="plot" value="Plot" />
					<h:inputText id="plot" maxlength="2000"
						value="#{addMovieBean.movie.plot}" />
					<h:message for="plot" style="color: red" />

					<h:outputLabel for="language" value="#{msg.language}" />
					<h:inputText id="language" maxlength="48"
						value="#{addMovieBean.movie.language}" />
					<h:message for="language" style="color: red" />

					<h:outputLabel for="country" value="#{msg.country}" />
					<h:inputText id="country" maxlength="48"
						value="#{addMovieBean.movie.country}" />
					<h:message for="country" style="color: red" />

					<h:outputLabel for="awards" value="Awards" />
					<h:inputText id="awards" maxlength="1000"
						value="#{addMovieBean.movie.awards}" />
					<h:message for="awards" style="color: red" />

					<h:outputLabel for="poster" value="Poster" />
					<h:inputText id="poster" maxlength="1000"
						validator="#{addMovieBean.validateUrl}"
						value="#{addMovieBean.movie.poster}" />
					<h:message for="poster" style="color: red" />

					<h:outputLabel for="rating" value="IMDB Rating" />
					<h:inputText id="rating" maxlength="20"
						value="#{addMovieBean.movie.imdbRating}" />
					<h:message for="rating" style="color: red" />

					<h:outputLabel for="votes" value="IMDB Votes" />
					<h:inputText id="votes" maxlength="9"
						value="#{addMovieBean.movie.imdbVotes}" />
					<h:message for="votes" style="color: red" />

					<h:outputLabel for="imdbId" value="IMDB ID" />
					<h:inputText id="imdbId" maxlength="9"
						value="#{addMovieBean.movie.imdbID}" />
					<h:message for="imdbId" style="color: red" />

					<h:outputLabel for="type" value="Type" />
					<h:inputText id="type" maxlength="20" required="true"
						value="#{addMovieBean.movie.type}" />
					<h:message for="type" style="color: red" />

				</h:panelGrid>

				<h:commandButton id="saveEvent" class="button"
					action="#{addMovieBean.save}" value="#{msg.save}" />
				<h:commandButton id="cancelEvent" class="button"
					action="#{addMovieBean.cancel}" value="#{msg.cancel}"
					immediate="true" />

			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>


WebContent/my_movies.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:mlzc="http://java.sun.com/jsf/composite/mlzcomp">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="content">
			<h:panelGroup rendered="#{myMoviesBean.movieDetail == null}">
				<h2>
					<h:outputText
						value="#{msg.my_movies} (#{myMoviesBean.storedMovies} stored movies)" />
				</h2>

				<mlzc:moives managedBeanMoviesDetail="#{myMoviesBean}" />

			</h:panelGroup>

			<h:panelGroup rendered="#{myMoviesBean.movieDetail != null}">
				<h2>
					<h:outputText value="Detail" />
				</h2>

				<mlzc:movieDetail movieDetail="#{myMoviesBean.movieDetail}" />

				<h:form id="form">

					<h:commandButton id="backEvent" class="button"
						action="#{myMoviesBean.close}" value="#{msg.back}" />
					<h:commandButton id="deleteEvent" class="button"
						action="#{myMoviesBean.delete}" value="#{msg.delete}" />

				</h:form>
			</h:panelGroup>

		</ui:define>
	</ui:composition>
</h:body>
</html>

WebContent/search_omdb.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:mlzc="http://java.sun.com/jsf/composite/mlzcomp">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="content">
			<h2>
				<h:outputText value="#{msg.search_omdb}" />
			</h2>

			<h:form id="formSearch">

				<h:panelGrid id="in_grid" columns="3">

					<h:outputLabel for="searchTitle" value="#{msg.title}" />
					<h:inputText id="searchTitle"
						value="#{movieSearchBean.searchTitle}">
						<f:validateRequired />
					</h:inputText>
					<h:message style="color: red" for="searchTitle" />

					<h:outputLabel for="searchYear" value="#{msg.year}" />
					<h:inputText id="searchYear" value="#{movieSearchBean.searchYear}">
						<f:validateRequired />
						<f:validateLongRange minimum="1660" maximum="2049" />
					</h:inputText>
					<h:message style="color: red" for="searchYear" />

				</h:panelGrid>

				<h:commandButton id="searchEvent" class="button"
					action="#{movieSearchBean.search}" value="#{msg.search}" />
				<h:commandButton id="cancelEvent" class="button"
					action="#{movieSearchBean.cancel}" value="#{msg.cancel}"
					immediate="true" />

			</h:form>

			<h:panelGroup rendered="#{movieSearchBean.movieDetail != null}">

				<mlzc:movieDetail movieDetail="#{movieSearchBean.movieDetail}" />

				<h:form id="formSave">
					<h:commandButton id="saveEvent" class="button"
						action="#{movieSearchBean.save}" value="#{msg.save}" />
					<h:commandButton id="backEvent" class="button"
						action="#{movieSearchBean.close}" value="#{msg.close}"
						immediate="true" />
				</h:form>
			</h:panelGroup>

			<h:panelGroup rendered="#{movieSearchBean.movies != null}">

				<mlzc:moives managedBeanMoviesDetail="#{movieSearchBean}" />

			</h:panelGroup>

		</ui:define>
	</ui:composition>
</h:body>
</html>
